name: Check auto-tagging will work

on:
  workflow_call

permissions: read-all

jobs:
  check-auto-tagging-will-work:
    if: ${{ ! startsWith(github.ref, 'refs/tags') && ! startsWith(github.ref, 'refs/heads/main') }}
    runs-on: ubuntu-latest

    steps:
      - name: Determine new tag version from PR body
        id: determine_next_tag
        uses: climatepolicyradar/get-next-tag-from-pr-body@v2
        with:
          pr_body: "${{ github.event.pull_request.body }}"
          pr_number: "${{ github.event.pull_request.number }}"

      - name: Auto-tagging will work
        run: |
          if [[ -z "${{ steps.determine_next_tag.outputs.new_tag }}" ]]; then
            exit 1;
          fi
