name: Python Precommit Validator

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        default: "3.9"
        type: string
      poetry-version:
        required: false
        default: 1.7.1
        type: string

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install "poetry==${{ inputs.poetry-version }}"
          poetry config virtualenvs.create false
          poetry install --no-cache
          poetry install --only-root

      - name: Export PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

      - name: Check pyproject.toml package version matches
        uses: climatepolicyradar/check-pyproject-package-version@v4

      - name: Check code contains no FIXME's
        run: |
          git grep -r --no-color ${case_sensitive} --line-number -e "FIXME" :^.github
          if [[ $? -eq 0 ]]; then
            # if we found any FIXME entries in checked in files, fail on main
            exit 1
          else
            exit 0
          fi
        shell: bash {0}

      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
        with:
          arguments: --ci
