name: Semver Tagging

on:
  workflow_call:
    inputs:
      repo-name:
        required: true
        type: string
      semver-tag:
        required: true
        type: string
      new-version:
        required: false
        type: string
      manual-semver:
        required: true
        type: string


jobs:
  semver:
    outputs:
      new_tag: ${{ steps.determine_next_tag.outputs.new_tag }}

    runs-on: ubuntu-latest
    steps:
      - name: Determine next tag
        id: determine_next_tag
        uses: climatepolicyradar/get-next-tag-from-pr-body@v3

      - run: echo ${{ steps.determine_next_tag.outputs.new_tag }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Retag latest SHA and push to ECR
        if: "${{ inputs.manual-semver == 'true' }}"
        id: retag_and_push_to_ecr
        uses: climatepolicyradar/retag-and-push-to-ecr@v1
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          repo-name: ${{ inputs.repo-name }}
          semver-tag: ${{ inputs.semver-tag }}

      - name: Retag latest SHA as merge commit with new tag and push to ECR
        if: "${{ inputs.new-version != '' && inputs.new-version != 'Skip' }}"
        id: retag_and_push_to_ecr_new_tag
        uses: climatepolicyradar/retag-and-push-to-ecr@v1
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          repo-name: ${{ inputs.repo-name }}
          semver-tag: ${{ inputs.semver-tag }}
          new-version: ${{ inputs.new-version }}

      - name: Retag latest SHA as merge commit with determined tag and push to ECR
        if: "${{ inputs.manual-semver != 'true' && steps.determine_next_tag.outputs.new_tag != '' && steps.determine_next_tag.outputs.new_tag != 'Skip' }}"
        id: retag_and_push_determined_tag_to_ecr
        uses: climatepolicyradar/retag-and-push-to-ecr@v1
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          repo-name: ${{ inputs.repo-name }}
          semver-tag: ${{ inputs.semver-tag }}
          new-version: ${{ steps.determine_next_tag.outputs.new_tag }}
