name: Auto Git & Semver Tagging

on:
  workflow_call:
    inputs:
      repo-name:
        required: true
        type: string
      semver-tag:
        required: true
        type: string

    outputs:
      new_tag:
        description: The next determined tag based on the last PR body
        value: ${{ jobs.determine-next.outputs.new_tag }}

    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      DOCKER_REGISTRY:
        required: true

jobs:
  determine-next:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}

    outputs:
      new_tag: ${{ steps.determine_next_tag.outputs.new_tag }}

    steps:
      - name: Determine new tag version
        id: determine_next_tag
        uses: climatepolicyradar/get-next-tag-from-pr-body@main

      - name: Next tag found?
        run: |
          if [[ -z "${{ steps.determine_next_tag.outputs.new_tag }}" ]]; then
            exit 1;
          fi

  semver:
    needs: determine-next
    if: ${{ github.ref == 'refs/heads/main' && needs.determine-next.outputs.new_tag != 'Skip'}}
    uses: climatepolicyradar/reusable-workflows/.github/workflows/semver.yml@main
    secrets: inherit
    with:
      repo-name: ${{ inputs.repo-name }}
      semver-tag: ${{ inputs.semver-tag }}
      new-version: ${{ needs.determine-next.outputs.new_tag }}

  git:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' && needs.determine-next.outputs.new_tag != 'Skip'}}
    permissions:
      contents: write
    needs:
      - determine-next
      - semver
    steps:
      - uses: actions/checkout@v4
      - uses: fregante/setup-git-user@v2

      - name: Create Git tag and push
        run: |
          echo "Attempting to auto-tag merge commit"
          new_tag=${{ needs.determine-next.outputs.new_tag }}
          new_version_num=${new_tag#v}
          git tag -a "${new_tag}" -m "Version ${new_version_num}"
          git push --tags origin "${new_tag}"
